steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/luzia', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/luzia']
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['beta', 'run', 'deploy', 'luzia-$BRANCH_NAME', '--no-allow-unauthenticated', '--image', 'gcr.io/$PROJECT_ID/luzia', '--region', 'us-east1','--platform', 'managed', '--quiet']
  images: ['gcr.io/$PROJECT_ID/luzia']
