// Code generated by protoc-gen-go. DO NOT EDIT.
// source: datacell/cell.proto

package datacell

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetLatestDataCellRequest struct {
	DataSource           string   `protobuf:"bytes,1,opt,name=DataSource,proto3" json:"DataSource,omitempty"`
	RowKey               string   `protobuf:"bytes,2,opt,name=RowKey,proto3" json:"RowKey,omitempty"`
	ColumnKey            string   `protobuf:"bytes,3,opt,name=ColumnKey,proto3" json:"ColumnKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLatestDataCellRequest) Reset()         { *m = GetLatestDataCellRequest{} }
func (m *GetLatestDataCellRequest) String() string { return proto.CompactTextString(m) }
func (*GetLatestDataCellRequest) ProtoMessage()    {}
func (*GetLatestDataCellRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f696549ad921725c, []int{0}
}

func (m *GetLatestDataCellRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLatestDataCellRequest.Unmarshal(m, b)
}
func (m *GetLatestDataCellRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLatestDataCellRequest.Marshal(b, m, deterministic)
}
func (m *GetLatestDataCellRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLatestDataCellRequest.Merge(m, src)
}
func (m *GetLatestDataCellRequest) XXX_Size() int {
	return xxx_messageInfo_GetLatestDataCellRequest.Size(m)
}
func (m *GetLatestDataCellRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLatestDataCellRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLatestDataCellRequest proto.InternalMessageInfo

func (m *GetLatestDataCellRequest) GetDataSource() string {
	if m != nil {
		return m.DataSource
	}
	return ""
}

func (m *GetLatestDataCellRequest) GetRowKey() string {
	if m != nil {
		return m.RowKey
	}
	return ""
}

func (m *GetLatestDataCellRequest) GetColumnKey() string {
	if m != nil {
		return m.ColumnKey
	}
	return ""
}

type GetDataCellRequest struct {
	DataSource           string   `protobuf:"bytes,1,opt,name=DataSource,proto3" json:"DataSource,omitempty"`
	RowKey               string   `protobuf:"bytes,2,opt,name=RowKey,proto3" json:"RowKey,omitempty"`
	ColumnKey            string   `protobuf:"bytes,3,opt,name=ColumnKey,proto3" json:"ColumnKey,omitempty"`
	RefKey               int64    `protobuf:"varint,4,opt,name=RefKey,proto3" json:"RefKey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataCellRequest) Reset()         { *m = GetDataCellRequest{} }
func (m *GetDataCellRequest) String() string { return proto.CompactTextString(m) }
func (*GetDataCellRequest) ProtoMessage()    {}
func (*GetDataCellRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f696549ad921725c, []int{1}
}

func (m *GetDataCellRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataCellRequest.Unmarshal(m, b)
}
func (m *GetDataCellRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataCellRequest.Marshal(b, m, deterministic)
}
func (m *GetDataCellRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataCellRequest.Merge(m, src)
}
func (m *GetDataCellRequest) XXX_Size() int {
	return xxx_messageInfo_GetDataCellRequest.Size(m)
}
func (m *GetDataCellRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataCellRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataCellRequest proto.InternalMessageInfo

func (m *GetDataCellRequest) GetDataSource() string {
	if m != nil {
		return m.DataSource
	}
	return ""
}

func (m *GetDataCellRequest) GetRowKey() string {
	if m != nil {
		return m.RowKey
	}
	return ""
}

func (m *GetDataCellRequest) GetColumnKey() string {
	if m != nil {
		return m.ColumnKey
	}
	return ""
}

func (m *GetDataCellRequest) GetRefKey() int64 {
	if m != nil {
		return m.RefKey
	}
	return 0
}

type GetDataCellResponse struct {
	AddedID              string   `protobuf:"bytes,1,opt,name=AddedID,proto3" json:"AddedID,omitempty"`
	RowKey               string   `protobuf:"bytes,2,opt,name=RowKey,proto3" json:"RowKey,omitempty"`
	ColumnKey            string   `protobuf:"bytes,3,opt,name=ColumnKey,proto3" json:"ColumnKey,omitempty"`
	RefKey               int64    `protobuf:"varint,4,opt,name=RefKey,proto3" json:"RefKey,omitempty"`
	Body                 string   `protobuf:"bytes,5,opt,name=Body,proto3" json:"Body,omitempty"`
	CreatedAt            string   `protobuf:"bytes,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDataCellResponse) Reset()         { *m = GetDataCellResponse{} }
func (m *GetDataCellResponse) String() string { return proto.CompactTextString(m) }
func (*GetDataCellResponse) ProtoMessage()    {}
func (*GetDataCellResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f696549ad921725c, []int{2}
}

func (m *GetDataCellResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDataCellResponse.Unmarshal(m, b)
}
func (m *GetDataCellResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDataCellResponse.Marshal(b, m, deterministic)
}
func (m *GetDataCellResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDataCellResponse.Merge(m, src)
}
func (m *GetDataCellResponse) XXX_Size() int {
	return xxx_messageInfo_GetDataCellResponse.Size(m)
}
func (m *GetDataCellResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDataCellResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDataCellResponse proto.InternalMessageInfo

func (m *GetDataCellResponse) GetAddedID() string {
	if m != nil {
		return m.AddedID
	}
	return ""
}

func (m *GetDataCellResponse) GetRowKey() string {
	if m != nil {
		return m.RowKey
	}
	return ""
}

func (m *GetDataCellResponse) GetColumnKey() string {
	if m != nil {
		return m.ColumnKey
	}
	return ""
}

func (m *GetDataCellResponse) GetRefKey() int64 {
	if m != nil {
		return m.RefKey
	}
	return 0
}

func (m *GetDataCellResponse) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *GetDataCellResponse) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type PutDataCellRequest struct {
	DataSource           string   `protobuf:"bytes,1,opt,name=DataSource,proto3" json:"DataSource,omitempty"`
	RowKey               string   `protobuf:"bytes,2,opt,name=RowKey,proto3" json:"RowKey,omitempty"`
	ColumnKey            string   `protobuf:"bytes,3,opt,name=ColumnKey,proto3" json:"ColumnKey,omitempty"`
	Body                 string   `protobuf:"bytes,4,opt,name=Body,proto3" json:"Body,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutDataCellRequest) Reset()         { *m = PutDataCellRequest{} }
func (m *PutDataCellRequest) String() string { return proto.CompactTextString(m) }
func (*PutDataCellRequest) ProtoMessage()    {}
func (*PutDataCellRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f696549ad921725c, []int{3}
}

func (m *PutDataCellRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutDataCellRequest.Unmarshal(m, b)
}
func (m *PutDataCellRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutDataCellRequest.Marshal(b, m, deterministic)
}
func (m *PutDataCellRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutDataCellRequest.Merge(m, src)
}
func (m *PutDataCellRequest) XXX_Size() int {
	return xxx_messageInfo_PutDataCellRequest.Size(m)
}
func (m *PutDataCellRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutDataCellRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutDataCellRequest proto.InternalMessageInfo

func (m *PutDataCellRequest) GetDataSource() string {
	if m != nil {
		return m.DataSource
	}
	return ""
}

func (m *PutDataCellRequest) GetRowKey() string {
	if m != nil {
		return m.RowKey
	}
	return ""
}

func (m *PutDataCellRequest) GetColumnKey() string {
	if m != nil {
		return m.ColumnKey
	}
	return ""
}

func (m *PutDataCellRequest) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func init() {
	proto.RegisterType((*GetLatestDataCellRequest)(nil), "datacell.getLatestDataCellRequest")
	proto.RegisterType((*GetDataCellRequest)(nil), "datacell.getDataCellRequest")
	proto.RegisterType((*GetDataCellResponse)(nil), "datacell.getDataCellResponse")
	proto.RegisterType((*PutDataCellRequest)(nil), "datacell.putDataCellRequest")
}

func init() { proto.RegisterFile("datacell/cell.proto", fileDescriptor_f696549ad921725c) }

var fileDescriptor_f696549ad921725c = []byte{
	// 300 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x35, 0x6d, 0x8c, 0x76, 0x3c, 0x88, 0x53, 0x90, 0x45, 0xaa, 0x94, 0x3d, 0xf5, 0x14, 0x41,
	0x7f, 0x41, 0x3f, 0xa0, 0x88, 0x3d, 0x48, 0x7a, 0x11, 0x6f, 0x6b, 0x76, 0x2c, 0x42, 0xec, 0xc6,
	0x64, 0x57, 0xe9, 0xc5, 0x83, 0x17, 0x7f, 0x8e, 0x7f, 0x51, 0xb2, 0xec, 0x1a, 0x5b, 0x2d, 0x7a,
	0x90, 0x5e, 0x42, 0xe6, 0xbd, 0x99, 0x37, 0x8f, 0xd9, 0x19, 0x68, 0x4b, 0xa1, 0x45, 0x4a, 0x59,
	0x76, 0x5a, 0x7d, 0xe2, 0xbc, 0x50, 0x5a, 0xe1, 0xae, 0x07, 0x79, 0x0e, 0x6c, 0x46, 0x7a, 0x22,
	0x34, 0x95, 0x7a, 0x24, 0xb4, 0x18, 0x52, 0x96, 0x25, 0xf4, 0x68, 0xa8, 0xd4, 0x78, 0x02, 0x50,
	0x41, 0x53, 0x65, 0x8a, 0x94, 0x58, 0xd0, 0x0d, 0x7a, 0xad, 0xe4, 0x0b, 0x82, 0x87, 0x10, 0x25,
	0xea, 0xf9, 0x92, 0x16, 0xac, 0x61, 0x39, 0x17, 0x61, 0x07, 0x5a, 0x43, 0x95, 0x99, 0x87, 0x79,
	0x45, 0x35, 0x2d, 0x55, 0x03, 0xfc, 0x35, 0x00, 0x9c, 0xd1, 0x66, 0x9a, 0xd9, 0x2a, 0xba, 0xab,
	0xa8, 0xb0, 0x1b, 0xf4, 0x9a, 0x89, 0x8b, 0xf8, 0x7b, 0x00, 0xed, 0x25, 0x13, 0x65, 0xae, 0xe6,
	0x25, 0x21, 0x83, 0x9d, 0xbe, 0x94, 0x24, 0x2f, 0x46, 0xce, 0x82, 0x0f, 0xff, 0xb7, 0x3f, 0x22,
	0x84, 0x03, 0x25, 0x17, 0x6c, 0xdb, 0x16, 0xd8, 0x7f, 0xab, 0x54, 0x90, 0xd0, 0x24, 0xfb, 0x9a,
	0x45, 0x4e, 0xc9, 0x03, 0xfc, 0x05, 0x30, 0x37, 0x1b, 0x9a, 0x9a, 0x77, 0x17, 0xd6, 0xee, 0xce,
	0xde, 0x1a, 0xb0, 0x2f, 0x5d, 0xf7, 0x29, 0x15, 0x4f, 0xf7, 0x29, 0xe1, 0x35, 0x1c, 0x8c, 0x57,
	0x97, 0x07, 0x79, 0xec, 0x97, 0x2b, 0x5e, 0xb7, 0x59, 0x47, 0xc7, 0x4b, 0x39, 0xab, 0xaf, 0xc0,
	0xb7, 0x70, 0x02, 0x7b, 0xe3, 0x9a, 0xc0, 0xce, 0x9a, 0xfc, 0xbf, 0xab, 0x5d, 0x99, 0x1f, 0xd5,
	0xbe, 0x8f, 0xf4, 0x57, 0xb5, 0x01, 0xdc, 0x7c, 0x9e, 0xcf, 0x6d, 0x64, 0xef, 0xe9, 0xfc, 0x23,
	0x00, 0x00, 0xff, 0xff, 0x53, 0x4b, 0x4f, 0x99, 0x66, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DataCellServiceClient is the client API for DataCellService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DataCellServiceClient interface {
	GetLatestDataCell(ctx context.Context, in *GetLatestDataCellRequest, opts ...grpc.CallOption) (*GetDataCellResponse, error)
	GetDataCell(ctx context.Context, in *GetDataCellRequest, opts ...grpc.CallOption) (*GetDataCellResponse, error)
	PutDataCell(ctx context.Context, in *PutDataCellRequest, opts ...grpc.CallOption) (*GetDataCellResponse, error)
}

type dataCellServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDataCellServiceClient(cc grpc.ClientConnInterface) DataCellServiceClient {
	return &dataCellServiceClient{cc}
}

func (c *dataCellServiceClient) GetLatestDataCell(ctx context.Context, in *GetLatestDataCellRequest, opts ...grpc.CallOption) (*GetDataCellResponse, error) {
	out := new(GetDataCellResponse)
	err := c.cc.Invoke(ctx, "/datacell.dataCellService/GetLatestDataCell", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataCellServiceClient) GetDataCell(ctx context.Context, in *GetDataCellRequest, opts ...grpc.CallOption) (*GetDataCellResponse, error) {
	out := new(GetDataCellResponse)
	err := c.cc.Invoke(ctx, "/datacell.dataCellService/GetDataCell", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *dataCellServiceClient) PutDataCell(ctx context.Context, in *PutDataCellRequest, opts ...grpc.CallOption) (*GetDataCellResponse, error) {
	out := new(GetDataCellResponse)
	err := c.cc.Invoke(ctx, "/datacell.dataCellService/PutDataCell", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DataCellServiceServer is the server API for DataCellService service.
type DataCellServiceServer interface {
	GetLatestDataCell(context.Context, *GetLatestDataCellRequest) (*GetDataCellResponse, error)
	GetDataCell(context.Context, *GetDataCellRequest) (*GetDataCellResponse, error)
	PutDataCell(context.Context, *PutDataCellRequest) (*GetDataCellResponse, error)
}

// UnimplementedDataCellServiceServer can be embedded to have forward compatible implementations.
type UnimplementedDataCellServiceServer struct {
}

func (*UnimplementedDataCellServiceServer) GetLatestDataCell(ctx context.Context, req *GetLatestDataCellRequest) (*GetDataCellResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetLatestDataCell not implemented")
}
func (*UnimplementedDataCellServiceServer) GetDataCell(ctx context.Context, req *GetDataCellRequest) (*GetDataCellResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDataCell not implemented")
}
func (*UnimplementedDataCellServiceServer) PutDataCell(ctx context.Context, req *PutDataCellRequest) (*GetDataCellResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutDataCell not implemented")
}

func RegisterDataCellServiceServer(s *grpc.Server, srv DataCellServiceServer) {
	s.RegisterService(&_DataCellService_serviceDesc, srv)
}

func _DataCellService_GetLatestDataCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetLatestDataCellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataCellServiceServer).GetLatestDataCell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datacell.dataCellService/GetLatestDataCell",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataCellServiceServer).GetLatestDataCell(ctx, req.(*GetLatestDataCellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataCellService_GetDataCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDataCellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataCellServiceServer).GetDataCell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datacell.dataCellService/GetDataCell",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataCellServiceServer).GetDataCell(ctx, req.(*GetDataCellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DataCellService_PutDataCell_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutDataCellRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DataCellServiceServer).PutDataCell(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/datacell.dataCellService/PutDataCell",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DataCellServiceServer).PutDataCell(ctx, req.(*PutDataCellRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _DataCellService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "datacell.dataCellService",
	HandlerType: (*DataCellServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetLatestDataCell",
			Handler:    _DataCellService_GetLatestDataCell_Handler,
		},
		{
			MethodName: "GetDataCell",
			Handler:    _DataCellService_GetDataCell_Handler,
		},
		{
			MethodName: "PutDataCell",
			Handler:    _DataCellService_PutDataCell_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "datacell/cell.proto",
}
